# Initial set of jobs that will be extended over time as
# we get things working.
- project:
    templates:
      - build-openstack-docs-pti
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
    check:
      jobs:
        - build-openstack-api-ref
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - openstack-tox-functional-py36
    gate:
      jobs:
        - build-openstack-api-ref
        - openstack-tox-functional
        - openstack-tox-functional-py35
        - openstack-tox-functional-py36
